### PR TITLE
Basic plugins support

### PR DESCRIPTION
**Pull request by Dimaqa**

### CODE REVIEW

**Comment by Dimaqa** [comment]
The thing is you can even get plugins choices from /api/plugins/installed-plugins/, but your plugins should have base_url equal to name in PluginConfig

**Comment by zachmoody** [comment]
Thanks, looks good. Do you mind throwing together a unit test for it in `test_app.py`?

**Comment by Dimaqa** [comment]
> Thanks, looks good. Do you mind throwing together a unit test for it in `test_app.py`?

Done

**Comment by MattIPv4** [comment]
Hey, @Dimaqa - Thanks a ton for this sweet PR! 😄

Would you please shoot me an email when you get a chance?
mcowley at digitalocean dot com 🎉

**Comment by Dimaqa** [comment]
Hey, @MattIPv4 . I've specified my email in profile.

**Comment by deliciouslytyped** [comment]
Looks like this didn't update the docstring listing valid attributes?

**Pull request merged**
