### PR TITLE
Add __getstate__ and __setstate__ methods in PluginsApp to fix #329

### LINKED ISSUE #329: Not possible to pickle objects
On pynetbox version higher than 5.0.8 it is not possible to pickle objects. Used for testing purposes in absence of Netbox.

pynetbox-5.3.1/pynetbox-5.1.1:
>>> nbox = pynetbox.api(NBOX_URL, token=NBOX_TOKEN)
>>> sites = nbox.dcim.sites.all()
>>> f = open("object.pickle", "wb")
>>> pickle.dump(sites, f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'App' object is not callable

pynetbox-5.0.8:
>>> nbox = pynetbox.api(NBOX_URL, token=NBOX_TOKEN)
>>> sites = nbox.dcim.sites.all()
>>> f = open("object.pickle", "wb")
>>> pickle.dump(sites, f)
>>> f.close()

### PR DESCRIPTION
**Pull request by markkuleinio**
My attempt to fix #329 (pickling problems with PluginsApp).

### CODE REVIEW

**Comment by raddessi** [comment]
@markkuleinio if you have a chance would you merge in the latest changes and see if the test suite passes now? Thanks :)

**Comment by markkuleinio** [comment]
No success: https://pastebin.com/yLmBEjCa

**Comment by raddessi** [comment]
Ah! You don't have docker installed! OK.. this is something I can work around. I apologize.. I should have thought of that. I'll send up a PR to skip integration tests if docker is not present.

**Comment by raddessi** [comment]
FYI however I do think the tests run via github workflows should pass if you merge upstream master in to this branch.

**Pull request merged**
